# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-x67cFvytcXWiDTSUWiA4cNPfoYaJG-
"""

import pandas as pd

df=pd.read_csv('/Salary_Data.csv')
df.head()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
le = LabelEncoder()

# Example usage:
# Assuming 'categorical_column' is a column in your DataFrame that contains categorical data.
# df['categorical_column_encoded'] = le.fit_transform(df['categorical_column'])

# Note: Your current DataFrame 'df' contains only numerical columns ('YearsExperience', 'Salary').
# Label Encoding is generally used for converting non-numeric (categorical) labels into numeric ones.
# If you intend to apply it to a specific column or have a categorical column not yet in the DataFrame, please specify.

from sklearn.model_selection import train_test_split

# Define features (X) and target variable (y)
X = df[['YearsExperience']]
y = df['Salary']

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### Training Data (Input and Output)"""

print("X_train (Input features - first 5 rows):")
display(X_train.head())

print("y_train (Output target - first 5 rows):")
display(y_train.head())

"""### Testing Data (Input and Output)"""

print("X_test (Input features - first 5 rows):")
display(X_test.head())

print("y_test (Output target - first 5 rows):")
display(y_test.head())

"""### Model Training"""

from sklearn.linear_model import LinearRegression

# Initialize and train the Linear Regression model
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

print("Linear Regression Model Trained.")

from sklearn.tree import DecisionTreeRegressor

# Initialize and train the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)
decision_tree_model.fit(X_train, y_train)

print("Decision Tree Regressor Model Trained.")

from sklearn.ensemble import RandomForestRegressor

# Initialize and train the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)
random_forest_model.fit(X_train, y_train)

print("Random Forest Regressor Model Trained.")

from sklearn.svm import SVR

# Initialize and train the Support Vector Regressor (SVR) model
# SVMs can be sensitive to scaling, but for this simple dataset, we'll proceed without explicit scaling for now.
svm_model = SVR()
svm_model.fit(X_train, y_train)

print("Support Vector Regressor (SVR) Model Trained.")

from sklearn.neighbors import KNeighborsRegressor

# Initialize and train the K-Nearest Neighbors Regressor (KNN) model
# The number of neighbors (n_neighbors) is a hyperparameter that can be tuned.
knn_model = KNeighborsRegressor(n_neighbors=5)
knn_model.fit(X_train, y_train)

print("K-Nearest Neighbors Regressor (KNN) Model Trained.")

"""### Model Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create predictions for each model
linear_reg_predictions = linear_reg_model.predict(X_test)
decision_tree_predictions = decision_tree_model.predict(X_test)
random_forest_predictions = random_forest_model.predict(X_test)
svm_predictions = svm_model.predict(X_test)
knn_predictions = knn_model.predict(X_test)

# Create a list of models and their predictions for easier iteration
models = {
    'Linear Regression': linear_reg_predictions,
    'Decision Tree': decision_tree_predictions,
    'Random Forest': random_forest_predictions,
    'SVR': svm_predictions,
    'KNN': knn_predictions
}

# Plotting predictions vs. actual values for each model
fig, axes = plt.subplots(len(models), 1, figsize=(10, 5 * len(models)))
fig.suptitle('Model Predictions vs. Actual Values', y=1.02, fontsize=16)

for i, (model_name, predictions) in enumerate(models.items()):
    sns.scatterplot(x=X_test['YearsExperience'], y=y_test, ax=axes[i], label='Actual Salary', color='blue', s=100)
    sns.scatterplot(x=X_test['YearsExperience'], y=predictions, ax=axes[i], label=f'{model_name} Predicted Salary', color='red', marker='x', s=100)
    axes[i].set_title(f'{model_name} Predictions')
    axes[i].set_xlabel('Years of Experience')
    axes[i].set_ylabel('Salary')
    axes[i].legend()
    axes[i].grid(True)

plt.tight_layout()
plt.show()

"""### Residuals Plot for Linear Regression Model"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate residuals for the Linear Regression model
linear_reg_residuals = y_test - linear_reg_predictions

# Create a residuals plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x=X_test['YearsExperience'], y=linear_reg_residuals, color='purple', s=100)
plt.axhline(y=0, color='red', linestyle='--', linewidth=2)
plt.title('Residuals Plot for Linear Regression Model')
plt.xlabel('Years of Experience')
plt.ylabel('Residuals (Actual - Predicted Salary)')
plt.grid(True)
plt.show()

"""### Model Performance Comparison"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd

# Make predictions for all models on the test set (already done in previous visualization cell, but re-running for clarity)
linear_reg_predictions = linear_reg_model.predict(X_test)
decision_tree_predictions = decision_tree_model.predict(X_test)
random_forest_predictions = random_forest_model.predict(X_test)
svm_predictions = svm_model.predict(X_test)
knn_predictions = knn_model.predict(X_test)

# Initialize a dictionary to store metrics
model_performance = {}

# List of models and their predictions
models = {
    'Linear Regression': linear_reg_predictions,
    'Decision Tree': decision_tree_predictions,
    'Random Forest': random_forest_predictions,
    'SVR': svm_predictions,
    'KNN': knn_predictions
}

# Calculate metrics for each model
for model_name, predictions in models.items():
    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)
    model_performance[model_name] = {'MAE': mae, 'MSE': mse, 'R2 Score': r2}

# Convert the dictionary to a DataFrame for better readability
performance_df = pd.DataFrame(model_performance).T.round(2)

print("Model Performance Comparison on Test Set:")
display(performance_df)

"""### Saving the Best Model"""

import pickle

# Based on the performance metrics, KNN and Linear Regression performed similarly well.
# Let's choose the KNN model as an example, as it had the lowest MAE.
best_model = knn_model
model_filename = 'best_knn_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model (KNN) saved as '{model_filename}'")